export const sports = [
    { label: "Fútbol", value: "futbol" },
    { label: "Baloncesto", value: "baloncesto" },
    { label: "Tenis", value: "tenis" },
    { label: "Voleibol", value: "voleibol" },
    { label: "Balonmano", value: "balonmano" },
    { label: "Béisbol", value: "beisbol" },
    { label: "Rugby", value: "rugby" },
    { label: "Hockey", value: "hockey" },
    { label: "Atletismo", value: "atletismo" },
    { label: "Natación", value: "natacion" },
    { label: "Gimnasia", value: "gimnasia" },
    { label: "Judo", value: "judo" },
    { label: "Karate", value: "karate" },
    { label: "Taekwondo", value: "taekwondo" },
    { label: "Boxeo", value: "boxeo" },
    { label: "Lucha", value: "lucha" },
    { label: "Esgrima", value: "esgrima" },
    { label: "Ciclismo", value: "ciclismo" },
    { label: "Pádel", value: "padel" },
    { label: "Bádminton", value: "badminton" },
    { label: "Tenis de Mesa", value: "tenis-de-mesa" },
    { label: "Golf", value: "golf" },
    { label: "Fútbol Americano", value: "futbol-americano" },
    { label: "Triatlón", value: "triatlon" },
    { label: "Waterpolo", value: "waterpolo" },
    { label: "Remo", value: "remo" },
    { label: "Vela", value: "vela" },
    { label: "Hípica", value: "hipica" },
    { label: "Tiro con Arco", value: "tiro-con-arco" },
    { label: "Escalada", value: "escalada" },
    { label: "Skateboarding", value: "skateboarding" },
    { label: "Surf", value: "surf" },
    { label: "Ajedrez", value: "ajedrez" },
];
