export const sports = [
    { label: "Ajedrez", value: "ajedrez" },
    { label: "Atletismo", value: "atletismo" },
    { label: "Automovilismo", value: "automovilismo" },
    { label: "Bádminton", value: "badminton" },
    { label: "Baloncesto", value: "baloncesto" },
    { label: "Balonmano", value: "balonmano" },
    { label: "Béisbol", value: "beisbol" },
    { label: "Biatlón", value: "biatlon" },
    { label: "Billar", value: "billar" },
    { label: "Bobsleigh", value: "bobsleigh" },
    { label: "Bolos", value: "bolos" },
    { label: "Boxeo", value: "boxeo" },
    { label: "Ciclismo", value: "ciclismo" },
    { label: "Críquet", value: "criquet" },
    { label: "Curling", value: "curling" },
    { label: "Dardos", value: "dardos" },
    { label: "Escalada", value: "escalada" },
    { label: "Esgrima", value: "esgrima" },
    { label: "Esquí alpino", value: "esqui-alpino" },
    { label: "Esquí de fondo", value: "esqui-de-fondo" },
    { label: "Fisicoculturismo", value: "fisicoculturismo" },
    { label: "Fútbol", value: "futbol" },
    { label: "Fútbol Americano", value: "futbol-americano" },
    { label: "Gimnasia", value: "gimnasia" },
    { label: "Golf", value: "golf" },
    { label: "Halterofilia", value: "halterofilia" },
    { label: "Hípica", value: "hipica" },
    { label: "Hockey", value: "hockey" },
    { label: "Judo", value: "judo" },
    { label: "Karate", value: "karate" },
    { label: "Kitesurf", value: "kitesurf" },
    { label: "Lacrosse", value: "lacrosse" },
    { label: "Lucha", value: "lucha" },
    { label: "Motociclismo", value: "motociclismo" },
    { label: "Natación", value: "natacion" },
    { label: "Pádel", value: "padel" },
    { label: "Patinaje artístico", value: "patinaje-artistico" },
    { label: "Pelota vasca", value: "pelota-vasca" },
    { label: "Pentatlón Moderno", value: "pentatlon-moderno" },
    { label: "Piragüismo", value: "piraguismo" },
    { label: "Polo", value: "polo" },
    { label: "Remo", value: "remo" },
    { label: "Rugby", value: "rugby" },
    { label: "Salto de esquí", value: "salto-de-esqui" },
    { label: "Skateboarding", value: "skateboarding" },
    { label: "Snowboard", value: "snowboard" },
    { label: "Squash", value: "squash" },
    { label: "Surf", value: "surf" },
    { label: "Taekwondo", value: "taekwondo" },
    { label: "Tenis", value: "tenis" },
    { label: "Tenis de Mesa", value: "tenis-de-mesa" },
    { label: "Tiro", value: "tiro" },
    { label: "Tiro con Arco", value: "tiro-con-arco" },
    { label: "Triatlón", value: "triatlon" },
    { label: "Vela", value: "vela" },
    { label: "Voleibol", value: "voleibol" },
    { label: "Waterpolo", value: "waterpolo" },
    { label: "Windsurf", value: "windsurf" },
];
