export const sports = [
    { label: "Fútbol", value: "futbol" },
    { label: "Baloncesto", value: "baloncesto" },
    { label: "Tenis", value: "tenis" },
    { label: "Voleibol", value: "voleibol" },
    { label: "Balonmano", value: "balonmano" },
    { label: "Béisbol", value: "beisbol" },
    { label: "Rugby", value: "rugby" },
    { label: "Hockey", value: "hockey" },
    { label: "Atletismo", value: "atletismo" },
    { label: "Natación", value: "natacion" },
    { label: "Gimnasia", value: "gimnasia" },
    { label: "Judo", value: "judo" },
    { label: "Karate", value: "karate" },
    { label: "Boxeo", value: "boxeo" },
    { label: "Ciclismo", value: "ciclismo" },
    { label: "Pádel", value: "padel" },
    { label: "Bádminton", value: "badminton" },
    { label: "Golf", value: "golf" },
    { label: "Fútbol Americano", value: "futbol-americano" },
    { label: "Esgrima", value: "esgrima" },
    { label: "Triatlón", value: "triatlon" },
    { label: "Waterpolo", value: "waterpolo" },
    { label: "Ajedrez", value: "ajedrez" },
    { label: "Ping Pong", value: "ping-pong" },
];
